# Generated by Django 5.1.2 on 2024-11-01 13:38

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                ("bank_code", models.CharField(max_length=10)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings Account"),
                            ("CHECKING", "Checking Account"),
                            ("CREDIT", "Credit Account"),
                            ("LOAN", "Loan Account"),
                        ],
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
            },
        ),
    ]
