# Generated by Django 5.1.2 on 2024-11-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction_History",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("post_transaction_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_details", models.CharField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAWAL", "출금")], max_length=10),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("CASH", "현금"), ("CARD", "카드"), ("TRANSFER", "이체")], max_length=10),
                ),
                ("transaction_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "account_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="accounts.accounts"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "db_table": "transaction_history",
            },
        ),
    ]
