# Generated by Django 5.1.2 on 2024-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_history",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("ATM", "ATM 거래"),
                    ("TRANSFER", "계좌이체"),
                    ("AUTOMATIC_TRANSFER", "자동이체"),
                    ("CARD", "카드결제"),
                    ("INTEREST", "이자"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction_history",
            name="transaction_type",
            field=models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], max_length=10),
        ),
    ]
