services:
  db:
    image:  mysql:8.0.34
    container_name: travel_plan
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: plan
      MYSQL_USER: localhost
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root