FROM python:3.12-slim

WORKDIR /MAIN_BLOG/app

ENV PYTHONPATH=/MAIN_BLOG:$PYTHONPATH

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./app /code/app

RUN echo '#!/bin/sh' > /start.sh
RUN echo 'alembic upgrade head' >> /start.sh
RUN echo 'uvicorn app.main:app --host 0.0.0.0 --port 8000' >> /start.sh
RUN chmod +x /start.sh

CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]